### ISSUE TITLE
Métodos de inserción para la propiedad Visits::data

### ISSUE THREAD

**Issue by Antobio17** [alexespana/Proyecto-IV#19]
Como programador voy a resolver el problema especificado en la historia de usuario #9 y para insertar datos en la propiedad especificada en #18 se van a realizar los siguientes métodos, definiendo así la estructura de la propiedad:

- add_visit(client_type, time): añadirá la visita de un tipo de cliente a la franja horaria correspondiente.
- add_product_consumed(product, time): añadirá el producto consumido a la franja horaria correspondiente.

**Comment by alexespana** [comment]
Si se diera el caso de que se añada un producto nuevo a la carta, ¿el método add_product añadirá dicha clave nueva al diccionario?

**Comment by Antobio17** [comment]
> Si se diera el caso de que se añada un producto nuevo a la carta, ¿el método add_product añadirá dicha clave nueva al diccionario?

La ideas es que a la función se le introduzca un _string_ con el nombre del producto. Si el producto ya ha sido registrado en ese valor de fecha se incrementaría el valor de consumido, en caso contrario se añadiría al diccionario con valor 1 (1 vez consumido por el momento).

**Comment by alexespana** [comment]
:+1:
